import { Router } from 'express';
import { randomBytes } from 'node:crypto';
import { AppError } from '../core/errors.mjs';
import { buildContactFilter } from '../core/segments.mjs';
import { boundedInteger, requireText, requireUuid } from '../core/validation.mjs';
import { enqueueRecipient } from '../queue/email-queue.mjs';

const token=()=>randomBytes(24).toString('base64url');
export function createCampaignRouter({db,auth,emailQueue,config}){const router=Router();router.use(auth);
  const load=async(id,tenant)=>{const {rows}=await db.query('select * from campaigns where id=$1 and tenant_id=$2',[id,tenant]);if(!rows[0])throw new AppError('CAMPAIGN_NOT_FOUND','Campaign not found',404);return rows[0]};
  router.get('/',async(req,res,next)=>{try{const {rows}=await db.query(`select c.*,m.email mailbox_email,m.provider mailbox_provider,(select count(*)::int from campaign_recipients r where r.campaign_id=c.id) recipients from campaigns c left join mailboxes m on m.id=c.mailbox_id where c.tenant_id=$1 order by c.created_at desc`,[req.auth.tenant_id]);res.json({ok:true,data:rows})}catch(e){next(e)}});
  router.post('/preview-count',async(req,res,next)=>{try{const filter=buildContactFilter(req.auth.tenant_id,req.body.segment||{});const count=(await db.query(`select count(*)::int count from contacts where ${filter.where}`,filter.values)).rows[0].count;res.json({ok:true,data:{count}})}catch(e){next(e)}});
  router.post('/',async(req,res,next)=>{try{const mailboxId=requireUuid(req.body.mailboxId,'mailboxId');const mailbox=(await db.query("select id,status from mailboxes where id=$1 and tenant_id=$2",[mailboxId,req.auth.tenant_id])).rows[0];if(!mailbox)throw new AppError('MAILBOX_NOT_FOUND','Mailbox not found',404);const {rows}=await db.query(`insert into campaigns (tenant_id,mailbox_id,name,subject_template,html_template,text_template,segment_definition,max_jitter_seconds,physical_address,sender_name) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,[req.auth.tenant_id,mailboxId,requireText(req.body.name,'name',{max:200}),requireText(req.body.subject,'subject',{max:500}),requireText(req.body.html,'html',{max:200000}),requireText(req.body.text||req.body.html.replace(/<[^>]+>/g,' '),'text',{max:200000}),JSON.stringify(req.body.segment||{}),boundedInteger(req.body.maxJitterSeconds,'maxJitterSeconds',0,3600,120),requireText(req.body.physicalAddress,'physicalAddress',{max:500}),requireText(req.body.senderName||'Jareed Soft','senderName',{max:120})]);res.status(201).json({ok:true,data:rows[0]})}catch(e){next(e)}});
  router.post('/:id/schedule',async(req,res,next)=>{const client=await db.connect();try{const campaign=await load(requireUuid(req.params.id),req.auth.tenant_id);if(!['draft','paused','failed'].includes(campaign.status))throw new AppError('CAMPAIGN_STATE_INVALID',`Campaign is ${campaign.status}`,409);const mailbox=(await client.query('select * from mailboxes where id=$1 and tenant_id=$2',[campaign.mailbox_id,req.auth.tenant_id])).rows[0];if(!mailbox||mailbox.status!=='healthy')throw new AppError('MAILBOX_NOT_HEALTHY','Verify the selected mailbox first',409);const scheduledAt=req.body.scheduledAt?new Date(req.body.scheduledAt):new Date();if(Number.isNaN(scheduledAt.getTime()))throw new AppError('VALIDATION_ERROR','scheduledAt is invalid',400);const filter=buildContactFilter(req.auth.tenant_id,campaign.segment_definition||{});await client.query('begin');const contacts=(await client.query(`select id,email from contacts where ${filter.where}`,filter.values)).rows;if(!contacts.length)throw new AppError('EMPTY_SEGMENT','No eligible contacts match this segment',409);for(const contact of contacts){await client.query(`insert into campaign_recipients (campaign_id,contact_id,email,tracking_token,unsubscribe_token) values ($1,$2,$3,$4,$5) on conflict (campaign_id,contact_id) do nothing`,[campaign.id,contact.id,contact.email,token(),token()])}if(campaign.status!=='draft')await client.query("update campaign_recipients set status='pending',updated_at=now() where campaign_id=$1 and status in ('queued','blocked','failed')",[campaign.id]);await client.query("update campaigns set status='scheduled',scheduled_at=$2,updated_at=now() where id=$1",[campaign.id,scheduledAt]);await client.query('commit');const recipients=(await db.query("update campaign_recipients set status='queued',queued_at=now(),updated_at=now() where campaign_id=$1 and status='pending' returning id",[campaign.id])).rows;try{for(const recipient of recipients)await enqueueRecipient(emailQueue,{campaignId:campaign.id,recipientId:recipient.id,mailboxId:mailbox.id,tenantId:req.auth.tenant_id},{scheduledAt,maxJitterMs:campaign.max_jitter_seconds*1000,jitterSecret:config.webhookSigningSecret})}catch(error){await db.query("update campaigns set status='failed',updated_at=now() where id=$1",[campaign.id]);await db.query("update campaign_recipients set status='pending',updated_at=now() where campaign_id=$1 and status='queued'",[campaign.id]);throw error}res.json({ok:true,data:{campaignId:campaign.id,queued:recipients.length,scheduledAt:scheduledAt.toISOString()}})}catch(e){await client.query('rollback').catch(()=>{});next(e)}finally{client.release()}});
  router.post('/:id/pause',async(req,res,next)=>{try{const id=requireUuid(req.params.id);const {rows}=await db.query("update campaigns set status='paused',updated_at=now() where id=$1 and tenant_id=$2 and status in ('scheduled','running') returning *",[id,req.auth.tenant_id]);if(!rows[0])throw new AppError('CAMPAIGN_STATE_INVALID','Campaign cannot be paused',409);res.json({ok:true,data:rows[0]})}catch(e){next(e)}});
  router.get('/:id/analytics',async(req,res,next)=>{try{const campaign=await load(requireUuid(req.params.id),req.auth.tenant_id);const {rows}=await db.query(`select count(*)::int total,count(*) filter(where status in ('accepted','delivered','opened','clicked','replied'))::int accepted,count(*) filter(where status='delivered')::int delivered,count(*) filter(where opened_at is not null)::int opened,count(*) filter(where clicked_at is not null)::int clicked,count(*) filter(where replied_at is not null)::int replied,count(*) filter(where status='bounced')::int bounced,count(*) filter(where status='failed')::int failed,count(*) filter(where status='blocked')::int blocked from campaign_recipients where campaign_id=$1`,[campaign.id]);res.json({ok:true,data:{campaign,metrics:rows[0]}})}catch(e){next(e)}});return router}
