import { Router } from 'express';
import { AppError } from '../core/errors.mjs';
import { buildContactFilter } from '../core/segments.mjs';
import { boundedInteger, requireEmail, requireText, requireUuid } from '../core/validation.mjs';

export function createContactRouter({db,auth}){const router=Router();router.use(auth);
  router.get('/',async(req,res,next)=>{try{const segment={query:req.query.q,university:req.query.university,specialization:req.query.specialization};const filter=buildContactFilter(req.auth.tenant_id,segment);const limit=boundedInteger(req.query.limit,'limit',1,500,100);filter.values.push(limit);const {rows}=await db.query(`select id,email,first_name,last_name,university,specialization,attributes,consent_basis,consent_source,consent_granted_at,created_at from contacts where ${filter.where} order by created_at desc limit $${filter.values.length}`,filter.values);res.json({ok:true,data:rows})}catch(e){next(e)}});
  router.post('/import',async(req,res,next)=>{const client=await db.connect();try{const contacts=req.body.contacts;if(!Array.isArray(contacts)||contacts.length<1||contacts.length>5000)throw new AppError('VALIDATION_ERROR','contacts must contain 1-5000 records',400);await client.query('begin');let imported=0;for(const item of contacts){const email=requireEmail(item.email);const basis=String(item.consentBasis||'');if(!['explicit_opt_in','legitimate_interest','contractual','legal_obligation'].includes(basis))throw new AppError('CONSENT_REQUIRED',`Consent basis is required for ${email}`,400);const source=requireText(item.consentSource,'consentSource',{max:500});await client.query(`insert into contacts (tenant_id,email,first_name,last_name,university,specialization,attributes,consent_basis,consent_source,consent_granted_at) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) on conflict (tenant_id,email) do update set first_name=excluded.first_name,last_name=excluded.last_name,university=excluded.university,specialization=excluded.specialization,attributes=excluded.attributes,consent_basis=excluded.consent_basis,consent_source=excluded.consent_source,consent_granted_at=excluded.consent_granted_at,consent_revoked_at=null,updated_at=now()`,[req.auth.tenant_id,email,item.firstName||null,item.lastName||null,item.university||null,item.specialization||null,JSON.stringify(item.attributes||{}),basis,source,item.consentGrantedAt?new Date(item.consentGrantedAt):new Date()]);imported++}await client.query('commit');res.status(201).json({ok:true,data:{imported}})}catch(e){await client.query('rollback').catch(()=>{});next(e)}finally{client.release()}});
  router.get('/universities',async(req,res,next)=>{try{const {rows}=await db.query('select university,count(*)::int contacts from contacts where tenant_id=$1 and university is not null group by university order by contacts desc',[req.auth.tenant_id]);res.json({ok:true,data:rows})}catch(e){next(e)}});
  router.delete('/:id',async(req,res,next)=>{try{const result=await db.query('delete from contacts where id=$1 and tenant_id=$2',[requireUuid(req.params.id),req.auth.tenant_id]);if(!result.rowCount)throw new AppError('CONTACT_NOT_FOUND','Contact not found',404);res.json({ok:true})}catch(e){next(e)}});return router}
