import { Router } from 'express';
import { AppError } from '../core/errors.mjs';
import { requireText, requireUuid } from '../core/validation.mjs';
import { extractResearch, getResearch, startResearch } from '../services/openai-research.mjs';
import { generateCampaignDraft } from '../services/openai-agent.mjs';

export function createKnowledgeRouter({db,auth,config}){const router=Router();router.use(auth);
  router.get('/universities',async(req,res,next)=>{try{const {rows}=await db.query(`select u.*,(select count(*)::int from research_runs r where r.university_id=u.id) research_runs from universities u where tenant_id=$1 order by created_at desc`,[req.auth.tenant_id]);res.json({ok:true,data:rows})}catch(e){next(e)}});
  router.get('/sources',async(req,res,next)=>{try{const {rows}=await db.query(`select s.id,s.url,s.title,s.fetched_at,s.status,s.metadata,u.name university_name from knowledge_sources s join universities u on u.id=s.university_id where u.tenant_id=$1 order by s.fetched_at desc nulls last limit 250`,[req.auth.tenant_id]);res.json({ok:true,data:rows})}catch(e){next(e)}});
  router.post('/universities',async(req,res,next)=>{try{const officialUrl=requireText(req.body.officialUrl,'officialUrl',{max:2000});const parsed=new URL(officialUrl);if(parsed.protocol!=='https:')throw new AppError('VALIDATION_ERROR','Official URL must use HTTPS',400);const {rows}=await db.query('insert into universities (tenant_id,name,country_code,official_url) values ($1,$2,$3,$4) returning *',[req.auth.tenant_id,requireText(req.body.name,'name',{max:300}),String(req.body.countryCode||'').toUpperCase()||null,parsed.toString()]);res.status(201).json({ok:true,data:rows[0]})}catch(e){next(e)}});
  router.post('/research',async(req,res,next)=>{try{const university=(await db.query('select * from universities where id=$1 and tenant_id=$2',[requireUuid(req.body.universityId,'universityId'),req.auth.tenant_id])).rows[0];if(!university)throw new AppError('UNIVERSITY_NOT_FOUND','University not found',404);const objective=requireText(req.body.objective,'objective',{min:10,max:5000});const run=(await db.query("insert into research_runs (tenant_id,university_id,objective,status,started_at) values ($1,$2,$3,'running',now()) returning *",[req.auth.tenant_id,university.id,objective])).rows[0];try{const response=await startResearch(config,{university,objective,mode:req.body.mode});await db.query('update research_runs set provider_response_id=$2 where id=$1',[run.id,response.id]);res.status(202).json({ok:true,data:{...run,provider_response_id:response.id,providerStatus:response.status}})}catch(error){await db.query("update research_runs set status='failed',error_detail=$2,completed_at=now() where id=$1",[run.id,error.message]);throw error}}catch(e){next(e)}});
  router.get('/research',async(req,res,next)=>{try{const {rows}=await db.query('select r.*,u.name university_name from research_runs r left join universities u on u.id=r.university_id where r.tenant_id=$1 order by r.created_at desc limit 100',[req.auth.tenant_id]);res.json({ok:true,data:rows})}catch(e){next(e)}});
  router.post('/research/:id/refresh',async(req,res,next)=>{try{const run=(await db.query('select * from research_runs where id=$1 and tenant_id=$2',[requireUuid(req.params.id),req.auth.tenant_id])).rows[0];if(!run)throw new AppError('RESEARCH_NOT_FOUND','Research run not found',404);if(!run.provider_response_id)throw new AppError('RESEARCH_PROVIDER_ID_MISSING','Research provider ID is missing',409);const response=await getResearch(config,run.provider_response_id);if(response.status==='completed'){const result=extractResearch(response);await db.query("update research_runs set status='completed',report_text=$2,citations=$3,evidence_count=$4,completed_at=now() where id=$1",[run.id,result.text,JSON.stringify(result.citations),result.citations.length]);for(const citation of result.citations){if(!citation.url)continue;await db.query(`insert into knowledge_sources (university_id,url,title,fetched_at,status,metadata) values ($1,$2,$3,now(),'fetched',$4) on conflict (university_id,url) do update set title=excluded.title,fetched_at=excluded.fetched_at,status='fetched',metadata=excluded.metadata`,[run.university_id,citation.url,citation.title||citation.url,JSON.stringify({researchRunId:run.id,responseId:run.provider_response_id})])}}else if(response.status==='failed'||response.status==='cancelled'){await db.query("update research_runs set status='failed',error_detail=$2,completed_at=now() where id=$1",[run.id,response.error?.message||response.status])}const updated=(await db.query('select * from research_runs where id=$1',[run.id])).rows[0];res.json({ok:true,data:updated})}catch(e){next(e)}});
  router.post('/agent/draft-campaign',async(req,res,next)=>{try{const draft=await generateCampaignDraft(config,{brief:requireText(req.body.brief,'brief',{min:10,max:5000}),audience:String(req.body.audience||''),language:String(req.body.language||'ar')});res.json({ok:true,data:draft})}catch(e){next(e)}});return router}
