import { Router } from 'express';
import { createHash, randomBytes } from 'node:crypto';
import { encryptCredential } from '../core/crypto.mjs';
import { AppError } from '../core/errors.mjs';

const sha=(value)=>createHash('sha256').update(value).digest('hex');
async function exchange(url,params){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)});const body=await response.json().catch(()=>({}));if(!response.ok||!body.access_token)throw new AppError('OAUTH_EXCHANGE_FAILED',body.error_description||body.error||`OAuth returned ${response.status}`,502);return body;}

export function createOAuthRouter({db,config,auth}) {
  const router=Router();
  async function newState(req,provider){const state=randomBytes(32).toString('base64url');const returnUri=String(req.query.returnUri||'');if(returnUri&&returnUri!=='com.jareed.soft://oauth')throw new AppError('RETURN_URI_INVALID','OAuth return URI is not allowed',400);await db.query('insert into oauth_states (state_hash,tenant_id,user_id,provider,return_uri,expires_at) values ($1,$2,$3,$4,$5,now()+interval \'10 minutes\')',[sha(state),req.auth.tenant_id,req.auth.user_id,provider,returnUri||null]);return state;}
  async function consume(state,provider){const {rows}=await db.query('update oauth_states set consumed_at=now() where state_hash=$1 and provider=$2 and consumed_at is null and expires_at>now() returning *',[sha(String(state||'')),provider]);if(!rows[0])throw new AppError('OAUTH_STATE_INVALID','OAuth state is invalid, expired, or already used',400);return rows[0];}

  router.get('/google/start',auth,async(req,res,next)=>{try{if(!config.google.clientId||!config.google.redirectUri)throw new AppError('GOOGLE_OAUTH_NOT_CONFIGURED','Google OAuth environment variables are missing',503);const state=await newState(req,'gmail');const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:config.google.clientId,redirect_uri:config.google.redirectUri,response_type:'code',access_type:'offline',prompt:'consent',scope:'openid email https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly',state}).toString();res.json({ok:true,data:{authorizationUrl:url.toString()}})}catch(e){next(e)}});
  router.get('/google/callback',async(req,res,next)=>{try{const state=await consume(req.query.state,'gmail');const token=await exchange('https://oauth2.googleapis.com/token',{client_id:config.google.clientId,client_secret:config.google.clientSecret,redirect_uri:config.google.redirectUri,code:String(req.query.code||''),grant_type:'authorization_code'});const profileRes=await fetch('https://www.googleapis.com/oauth2/v2/userinfo',{headers:{Authorization:`Bearer ${token.access_token}`}});const profile=await profileRes.json();if(!profileRes.ok||!profile.email)throw new AppError('OAUTH_PROFILE_FAILED','Could not read Google mailbox identity',502);const envelope=encryptCredential(JSON.stringify({accessToken:token.access_token,refreshToken:token.refresh_token,expiresAt:Date.now()+Number(token.expires_in||3600)*1000}),config.credentialKey);await db.query(`insert into mailboxes (tenant_id,provider,email,display_name,credential_envelope,status,provider_metadata) values ($1,'gmail',$2,$3,$4,'pending',$5) on conflict (tenant_id,email) do update set credential_envelope=excluded.credential_envelope,provider='gmail',status='pending',updated_at=now()`,[state.tenant_id,profile.email,profile.name||profile.email,envelope,JSON.stringify({googleId:profile.id})]);res.redirect(state.return_uri||`${config.webOrigin}/?oauth=google_success`)}catch(e){next(e)}});

  router.get('/microsoft/start',auth,async(req,res,next)=>{try{if(!config.microsoft.clientId||!config.microsoft.redirectUri)throw new AppError('MICROSOFT_OAUTH_NOT_CONFIGURED','Microsoft OAuth environment variables are missing',503);const state=await newState(req,'microsoft_graph');const tenant=config.microsoft.tenant||'common';const url=new URL(`https://login.microsoftonline.com/${encodeURIComponent(tenant)}/oauth2/v2.0/authorize`);url.search=new URLSearchParams({client_id:config.microsoft.clientId,redirect_uri:config.microsoft.redirectUri,response_type:'code',response_mode:'query',scope:'offline_access User.Read Mail.ReadWrite Mail.Send',state}).toString();res.json({ok:true,data:{authorizationUrl:url.toString()}})}catch(e){next(e)}});
  router.get('/microsoft/callback',async(req,res,next)=>{try{const state=await consume(req.query.state,'microsoft_graph');const tenant=config.microsoft.tenant||'common';const token=await exchange(`https://login.microsoftonline.com/${encodeURIComponent(tenant)}/oauth2/v2.0/token`,{client_id:config.microsoft.clientId,client_secret:config.microsoft.clientSecret,redirect_uri:config.microsoft.redirectUri,code:String(req.query.code||''),grant_type:'authorization_code',scope:'offline_access User.Read Mail.ReadWrite Mail.Send'});const profileRes=await fetch('https://graph.microsoft.com/v1.0/me?$select=id,displayName,mail,userPrincipalName',{headers:{Authorization:`Bearer ${token.access_token}`}});const profile=await profileRes.json();const email=profile.mail||profile.userPrincipalName;if(!profileRes.ok||!email)throw new AppError('OAUTH_PROFILE_FAILED','Could not read Microsoft mailbox identity',502);const envelope=encryptCredential(JSON.stringify({accessToken:token.access_token,refreshToken:token.refresh_token,expiresAt:Date.now()+Number(token.expires_in||3600)*1000}),config.credentialKey);await db.query(`insert into mailboxes (tenant_id,provider,email,display_name,credential_envelope,status,provider_metadata) values ($1,'microsoft_graph',$2,$3,$4,'pending',$5) on conflict (tenant_id,email) do update set credential_envelope=excluded.credential_envelope,provider='microsoft_graph',status='pending',updated_at=now()`,[state.tenant_id,email,profile.displayName||email,envelope,JSON.stringify({microsoftId:profile.id})]);res.redirect(state.return_uri||`${config.webOrigin}/?oauth=microsoft_success`)}catch(e){next(e)}});
  return router;
}
