import { Router } from 'express';
import { emailSuppressionHash } from '../core/crypto.mjs';
import { AppError } from '../core/errors.mjs';
import { validClickSignature } from '../core/tracking.mjs';

const pixel=Buffer.from('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==','base64');
export function createPublicRouter({db,config}){const router=Router();
  router.get('/open/:token/:messageId.gif',async(req,res)=>{try{const {rows}=await db.query(`update scheduled_messages sm set status=case when sm.status in ('SENT','DELIVERED') then 'OPENED' else sm.status end,updated_at=now()
      from campaign_recipients r,campaigns c where sm.id=$2 and sm.campaign_recipient_id=r.id and r.campaign_id=c.id and r.tracking_token=$1
      returning r.id campaign_recipient_id,c.tenant_id`,[req.params.token,req.params.messageId]);if(rows[0]){await db.query("update campaign_recipients set opened_at=coalesce(opened_at,now()),status=case when status in ('accepted','delivered') then 'opened' else status end,updated_at=now() where id=$1",[rows[0].campaign_recipient_id]);await db.query("insert into delivery_events (tenant_id,campaign_recipient_id,event_type,detail) values ($1,$2,'opened',$3)",[rows[0].tenant_id,rows[0].campaign_recipient_id,JSON.stringify({scheduledMessageId:req.params.messageId})])}}catch{}res.set({'Content-Type':'image/gif','Cache-Control':'no-store, no-cache, must-revalidate'}).send(pixel)});
  router.get('/click/:messageId',async(req,res,next)=>{try{const target=String(req.query.target||'');if(!validClickSignature({messageId:req.params.messageId,target,signature:req.query.sig,secret:config.webhookSigningSecret}))throw new AppError('CLICK_SIGNATURE_INVALID','رابط التتبع غير صالح.',400);const url=new URL(Buffer.from(target,'base64url').toString('utf8'));if(!['http:','https:'].includes(url.protocol))throw new AppError('CLICK_TARGET_INVALID','وجهة الرابط غير صالحة.',400);const {rows}=await db.query(`update scheduled_messages sm set status=case when sm.status in ('SENT','DELIVERED','OPENED') then 'CLICKED' else sm.status end,updated_at=now()
      from campaign_recipients r where sm.id=$1 and sm.campaign_recipient_id=r.id returning r.id campaign_recipient_id,sm.tenant_id`,[req.params.messageId]);if(rows[0]){await db.query("update campaign_recipients set clicked_at=coalesce(clicked_at,now()),status=case when status in ('accepted','delivered','opened') then 'clicked' else status end,updated_at=now() where id=$1",[rows[0].campaign_recipient_id]);await db.query("insert into delivery_events (tenant_id,campaign_recipient_id,event_type,detail) values ($1,$2,'clicked',$3)",[rows[0].tenant_id,rows[0].campaign_recipient_id,JSON.stringify({scheduledMessageId:req.params.messageId,target:url.toString()})])}res.redirect(302,url.toString())}catch(e){next(e)}});
  router.get('/open/:token.gif',async(req,res)=>{try{const {rows}=await db.query(`update campaign_recipients set opened_at=now(),status=case when status in ('accepted','delivered') then 'opened' else status end,updated_at=now() where tracking_token=$1 and opened_at is null returning id,campaign_id`,[req.params.token]);if(rows[0]){const tenant=(await db.query('select tenant_id from campaigns where id=$1',[rows[0].campaign_id])).rows[0];if(tenant)await db.query("insert into delivery_events (tenant_id,campaign_recipient_id,event_type) values ($1,$2,'opened')",[tenant.tenant_id,rows[0].id])}}catch{}res.set({'Content-Type':'image/gif','Cache-Control':'no-store, no-cache, must-revalidate'}).send(pixel)});
  const unsubscribe=async(req,res,next)=>{try{const {rows}=await db.query(`select r.id,r.contact_id,r.email,c.tenant_id from campaign_recipients r join campaigns c on c.id=r.campaign_id where r.unsubscribe_token=$1`,[req.params.token]);const row=rows[0];if(!row)throw new AppError('UNSUBSCRIBE_TOKEN_INVALID','Unsubscribe link is invalid',404);await db.query(`insert into suppressions (tenant_id,email_hash,reason,source) values ($1,$2,'unsubscribe','one_click') on conflict (tenant_id,email_hash) do nothing`,[row.tenant_id,emailSuppressionHash(row.email)]);await db.query('update contacts set consent_revoked_at=now(),updated_at=now() where id=$1',[row.contact_id]);await db.query("update scheduled_messages set status='CANCELLED',last_error_code='UNSUBSCRIBED',updated_at=now() where campaign_recipient_id=$1 and status in ('SCHEDULED','QUEUED')",[row.id]);res.status(200).type('html').send('<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><title>تم إلغاء الاشتراك</title><body style="font-family:Arial;padding:40px"><h1>تم إلغاء الاشتراك</h1><p>لن تُرسل إليك حملات أخرى من مساحة العمل هذه.</p></body></html>')}catch(e){next(e)}};
  router.get('/unsubscribe/:token',unsubscribe);router.post('/unsubscribe/:token',unsubscribe);return router}
