import { Router } from 'express';
import { emailSuppressionHash } from '../core/crypto.mjs';
import { AppError } from '../core/errors.mjs';

const pixel=Buffer.from('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==','base64');
export function createPublicRouter({db}){const router=Router();
  router.get('/open/:token.gif',async(req,res)=>{try{const {rows}=await db.query(`update campaign_recipients set opened_at=now(),status=case when status in ('accepted','delivered') then 'opened' else status end,updated_at=now() where tracking_token=$1 and opened_at is null returning id,campaign_id`,[req.params.token]);if(rows[0]){const tenant=(await db.query('select tenant_id from campaigns where id=$1',[rows[0].campaign_id])).rows[0];if(tenant)await db.query("insert into delivery_events (tenant_id,campaign_recipient_id,event_type) values ($1,$2,'opened')",[tenant.tenant_id,rows[0].id])}}catch{}res.set({'Content-Type':'image/gif','Cache-Control':'no-store, no-cache, must-revalidate'}).send(pixel)});
  const unsubscribe=async(req,res,next)=>{try{const {rows}=await db.query(`select r.id,r.contact_id,r.email,c.tenant_id from campaign_recipients r join campaigns c on c.id=r.campaign_id where r.unsubscribe_token=$1`,[req.params.token]);const row=rows[0];if(!row)throw new AppError('UNSUBSCRIBE_TOKEN_INVALID','Unsubscribe link is invalid',404);await db.query(`insert into suppressions (tenant_id,email_hash,reason,source) values ($1,$2,'unsubscribe','one_click') on conflict (tenant_id,email_hash) do nothing`,[row.tenant_id,emailSuppressionHash(row.email)]);await db.query('update contacts set consent_revoked_at=now(),updated_at=now() where id=$1',[row.contact_id]);res.status(200).type('html').send('<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><title>تم إلغاء الاشتراك</title><body style="font-family:Arial;padding:40px"><h1>تم إلغاء الاشتراك</h1><p>لن تُرسل إليك حملات أخرى من مساحة العمل هذه.</p></body></html>')}catch(e){next(e)}};
  router.get('/unsubscribe/:token',unsubscribe);router.post('/unsubscribe/:token',unsubscribe);return router}
