import { useQuery } from '@tanstack/react-query';
import { BarChart3 } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Card, EmptyState, ErrorState, LoadingState, PageHeader } from '../components/ui';
import { api } from '../lib/api';
import { formatNumber, formatPercent } from '../lib/format';
import type { DashboardData, SenderAnalytics } from '../types';

export function AnalyticsPage() {
  const query = useQuery({ queryKey: ['analytics'], queryFn: ({ signal }) => api.get<DashboardData>('/analytics/overview', signal).then((r) => r.data) });
  const senders = useQuery({ queryKey: ['analytics', 'senders'], queryFn: ({ signal }) => api.get<SenderAnalytics[]>('/analytics/senders', signal).then((r) => r.data) });
  if (query.isPending) return <><PageHeader title="التحليلات"/><LoadingState rows={7}/></>;
  if (query.isError) return <><PageHeader title="التحليلات"/><ErrorState error={query.error} onRetry={() => query.refetch()}/></>;
  if (!query.data.sent) return <><PageHeader title="التحليلات" description="مؤشرات مقاسة من أحداث الإرسال الفعلية"/><Card><EmptyState icon={<BarChart3 size={28}/>} title="لا توجد بيانات بعد" description="تظهر الرسوم بعد بدء الإرسال ووصول أحداث المزود."/></Card></>;
  return <><PageHeader title="التحليلات" description="مؤشرات مقاسة من أحداث الإرسال الفعلية"/><section className="metric-grid metric-grid--primary">{[['المرسل', query.data.sent],['التسليم',query.data.delivered],['الردود',query.data.replies],['المرتد',query.data.bounced]].map(([label,value]) => <Card className="metric-card" key={label as string}><strong>{formatNumber(value as number)}</strong><p>{label}</p></Card>)}</section><Card className="chart-card"><div className="card-heading"><div><h2>الأداء اليومي</h2><p>إرسال وتسليم وردود مقاسة</p></div></div><div className="chart-wrap" dir="ltr"><ResponsiveContainer width="100%" height="100%"><AreaChart data={query.data.dailySeries}><CartesianGrid strokeDasharray="3 5" stroke="#e6e9ef" vertical={false}/><XAxis dataKey="date" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="sent" name="المرسل" stroke="#0f766e" fill="#0f766e22"/><Area type="monotone" dataKey="delivered" name="المسلّم" stroke="#35a677" fill="#35a67711"/><Area type="monotone" dataKey="replies" name="الردود" stroke="#7c6ee6" fill="#7c6ee611"/></AreaChart></ResponsiveContainer></div></Card><Card className="table-card" style={{marginTop:16}}><div className="card-heading" style={{padding:16}}><div><h2>مقارنة حسابات الإرسال</h2><p>لا تُحتسب إلا الأحداث القابلة للقياس</p></div></div>{senders.isPending ? <LoadingState/> : senders.isError ? <ErrorState error={senders.error} onRetry={() => senders.refetch()}/> : <div className="responsive-table-wrap"><table className="data-table"><thead><tr><th>الحساب</th><th>المرسل</th><th>التسليم</th><th>الردود</th><th>المرتد</th><th>الفشل</th></tr></thead><tbody>{senders.data.map((sender) => <tr key={sender.id}><td dir="ltr">{sender.email}</td><td>{formatNumber(sender.sent)}</td><td>{formatNumber(sender.delivered)} <small>{formatPercent(sender.delivered,sender.sent)}</small></td><td>{formatNumber(sender.replies)} <small>{formatPercent(sender.replies,sender.sent)}</small></td><td>{formatNumber(sender.bounced)}</td><td>{formatNumber(sender.failed)}</td></tr>)}</tbody></table></div>}</Card></>;
}
